version: '3'
services:
    mariadb:
        image: i_mariadb
        volumes:
            - /home/ak1337/data/db:/var/lib/mysql
        restart: always
        environment:
            MARIADB_ROOT_PASS: "${MARIADB_ROOT_PASS}"
            MARIADB_DATABASE: "${MARIADB_DATABASE}"
            MARIADB_LOGIN: "${MARIADB_LOGIN}"
            MARIADB_PASS: "${MARIADB_PASS}"
        ports: 
            - "3306:3306"
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile 
        networks:
            - wp-site
        env_file: .env
        
    wordpress:
        depends_on:
            - mariadb
        image: i_wordpress
        volumes:
            - /home/ak1337/data/wp:/var/www/wordpress
        restart: always
        environment:
            WPADMIN_LOGIN: "${WPADMIN_LOGIN}"
            WPADMIN_PASS: "${WPADMIN_PASS}"
            WPUSER_LOGIN: "${WPUSER_LOGIN}"
            WPUSER_PASS: "${WPUSER_PASS}"
            MARIADB_LOGIN: "${MARIADB_LOGIN}"
            MARIADB_PASS: "${MARIADB_PASS}"
        ports:
            - "9000:9000"
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        networks:
            - wp-site
        env_file: .env
    nginx:
        image: i_nginx
        restart: always
        depends_on:
            - wordpress
        ports:
             - "443:443"
        volumes:
            - /home/ak1337/data/wp:/var/www/wordpress
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        networks:
            - wp-site
        extra_hosts:
            - "akezanna.42.fr:127.0.0.1"
            - "www.akezanna.42.fr:127.0.0.1"
        env_file: .env

networks:
    wp-site:
        driver: bridge


